=== RuidsCosta/PRI-1920/TPC/TPC_2_PRI/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ProjectRecord (KeyName, Title, Subtitle, BegDate, EnDate, Supervisor, WorkTeam, Abstract, Deliverables) >
<!ELEMENT KeyName (#PCDATA) >
<!ELEMENT Title (#PCDATA) >
<!ELEMENT Subtitle (#PCDATA) >
<!ELEMENT BegDate (#PCDATA) >
<!ELEMENT EnDate (#PCDATA) >
<!ELEMENT Supervisor (#PCDATA) >

<!ELEMENT WorkTeam (Member)+ >
<!ELEMENT Member (MemberName, MemberMail) >
<!ELEMENT MemberName (#PCDATA) >
<!ELEMENT MemberMail (#PCDATA) >

<!ELEMENT Abstract (Word)+ >
<!ELEMENT Word (Regular, Bold, Italic) >

<!ELEMENT Deliverables (Link)* >
<!ELEMENT Link (#PCDATA) >

<!ATTLIST Word
            Regular CDATA #IMPLIED 
            BOLD CDATA #IMPLIED
            ITALIC CDATA #IMPLIED>

<!ATTLIST Supervisor 
            link CDATA #REQUIRED>
        
<!ATTLIST Link 
            link CDATA #IMPLIED>

=== RuidsCosta/PRI-1920/TPC/TPC_2_PRI/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Abstract SYSTEM "file:/Users/ruicosta/Desktop/TPC_2_PRI/pr.dtd">

<ProjectRecord>
    <KeyName> PRI-1920-79947-TPC2</KeyName>
    <Title>Create a dtd ofr a project Record</Title>
    <Subtitle>Dtd</Subtitle>
    <BegDate>4 de outubro</BegDate>
    <EnDate>6 de outubro</EnDate>
    <Supervisor link="http://www4.di.uminho.pt/~jcr/"></Supervisor>
    <WorkTeam>
        <Member>
            <MemberName>Rui Costa</MemberName>
            <MemberMail>a79947@alunos.uminho.pt</MemberMail>
        </Member>
    </WorkTeam>
    <Abstract>
        <Word>
            <Regular>Hello World</Regular>
            <Bold></Bold>
            <Italic></Italic>
        </Word>
    </Abstract>
    <Deliverables>http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.html </Deliverables>
</ProjectRecord>
